# Generated by Django 4.2 on 2023-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cloud', '0002_remove_palavra_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive_arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('link_download', models.URLField()),
            ],
        ),
    ]
